# Generated by Django 4.2.11 on 2024-04-25 21:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manografia_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=100)),
                ('orientador', models.CharField(max_length=100)),
                ('coorientador', models.CharField(max_length=100)),
                ('resumo', models.TextField()),
                ('palavras_chave', models.CharField(max_length=150)),
                ('data_entrega', models.DateField()),
                ('banca_examinadora', models.CharField(max_length=300)),
                ('nota_final', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('area_concentracao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='', verbose_name='pdf')),
                ('manografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manografia_models')),
            ],
            options={
                'verbose_name': 'pdf',
                'verbose_name_plural': 'pdfs',
                'ordering': ('pk',),
            },
        ),
    ]
