# Generated by Django 4.2.11 on 2024-05-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_discente_docente_alter_arquivopdf_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discente',
            name='matricula',
            field=models.IntegerField(verbose_name=11),
        ),
    ]
