# Generated by Django 4.2.11 on 2024-05-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_discente_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discente',
            name='matricula',
            field=models.IntegerField(),
        ),
    ]
