# Generated by Django 4.2.11 on 2024-05-09 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_discente_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manografia_models',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.discente'),
        ),
        migrations.AlterField(
            model_name='manografia_models',
            name='orientador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.docente'),
        ),
    ]
