# Generated by Django 4.2.11 on 2024-05-12 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_manografia_models_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discente',
            name='matricula',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='manografia_models',
            name='coorientador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manografias_coorientadas', to='app.docente'),
        ),
        migrations.AlterField(
            model_name='manografia_models',
            name='orientador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manografias_orientadas', to='app.docente'),
        ),
    ]
