# Generated by Django 4.2.11 on 2024-06-06 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_alter_discente_matricula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManografiaAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_manografia', models.CharField(blank=True, max_length=500)),
                ('acao', models.CharField(max_length=50)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('detalhes', models.TextField()),
                ('manografia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.manografia_models')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
